default: &default
  adapter: postgresql
  encoding: UTF8
  url: "<%= ENV['DATABASE_URL'] %>?pool=<%= ENV['CONNECTION_POOL'] || 5 %>"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
